title: PianoByCassie
description: The Cassandria Barlow-Mayfield piano studio.

url: https://pianobycassie.com   # with https protocl
enforce_ssl: www.pianobycassie.com   # without any protocol
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Services
   url: /services
 - title: Philosophy
   url: /philosophy
 - title: Bio
   url: /bio
 - title: Répertoire
   url: /repertoire
 - title: Testimonials
   url: /testimonials
 - title: Contact
   url: /contact

social:
#   github: 
   twitter: pianistinmotion
   facebook: cassie.b.mayfield
   instagram: cassmayfield
   email: info@pianobycassie.com

google_analytics: "UA-79070913-2"
